= XML Glossary

This glossary explains terms used in articles of xref:XML.adoc[XML Reference]. It was generated by the xs3p
stylesheet.

Abstract::
  (Applies to complex type definitions and element declarations). An abstract element or complex type cannot used to
  validate an element instance. If there is a reference to an abstract element, only element declarations that can
  substitute the abstract element can be used to validate the instance. For references to abstract type definitions,
  only derived types can be used.

All Model Group::
  Child elements can be provided in any order in instances. See: https://www.w3.org/TR/xmlschema-1/#element-all.

Choice Model Group::
  Only one from the list of child elements and model groups can be provided in instances. See:
  https://www.w3.org/TR/xmlschema-1/#element-choice.

Collapse Whitespace Policy::
  Replace tab, line feed, and carriage return characters with space character (Unicode character 32). Then, collapse
  contiguous sequences of space characters into single space character, and remove leading and trailing space
  characters.

Disallowed Substitutions::
  (Applies to element declarations). If substitution is specified, then substitution group members cannot be used in
  place of the given element declaration to validate element instances. If derivation methods, e.g. extension,
  restriction, are specified, then the given element declaration will not validate element instances that have types
  derived from the element declaration's type using the specified derivation methods. Normally, element instances can
  override their declaration's type by specifying an xsi:type attribute.

Key Constraint::
  Like Uniqueness Constraint, but additionally requires that the specified value(s) must be provided. See:
  https://www.w3.org/TR/xmlschema-1/#cIdentity-constraint_Definitions.

Key Reference::
  Constraint Ensures that the specified value(s) must match value(s) from a Key Constraint or Uniqueness Constraint.
  See: https://www.w3.org/TR/xmlschema-1/#cIdentity-constraint_Definitions.

Model Group::
  Groups together element content, specifying the order in which the element content can occur and the number of times
  the group of element content may be repeated. See: https://www.w3.org/TR/xmlschema-1/#Model_Groups.

Nillable (Applies to element declarations).::
  If an element declaration is nillable, instances can use the xsi:nil attribute. The xsi:nil attribute is the boolean
  attribute, nil, from the https://www.w3.org/2001/XMLSchema-instance namespace. If an element instance has an xsi:nil
  attribute set to true, it can be left empty, even though its element declaration may have required content.

Notation::
  A notation is used to identify the format of a piece of data. Values of elements and attributes that are of type,
  NOTATION, must come from the names of declared notations. See:
  https://www.w3.org/TR/xmlschema-1/#cNotation_Declarations.

Preserve Whitespace::
  Policy Preserve whitespaces exactly as they appear in instances.

Prohibited Derivations (Applies to type definitions).::
  Derivation methods that cannot be used to create sub-types from a given type definition.

Prohibited Substitutions (Applies to complex type definitions).::
  Prevents sub-types that have been derived using the specified derivation methods from validating element instances in
  place of the given type definition.

Replace Whitespace Policy::
  Replace tab, line feed, and carriage return characters with space character (Unicode character 32).

Sequence Model Group::
  Child elements and model groups must be provided in the specified order in instances. See:
  https://www.w3.org/TR/xmlschema-1/#element-sequence.

Substitution Group::
  Elements that are members of a substitution group can be used wherever the head element of the substitution group is
  referenced.

Substitution Group Exclusions (Applies to element declarations).::
  Prohibits element declarations from nominating themselves as being able to substitute a given element declaration, if
  they have types that are derived from the original element's type using the specified derivation methods.

Target Namespace::
  The target namespace identifies the namespace that components in this schema belongs to. If no target namespace is
  provided, then the schema components do not belong to any namespace.

Uniqueness Constraint::
  Ensures uniqueness of an element/attribute value, or a combination of values, within a specified scope. See:
  https://www.w3.org/TR/xmlschema-1/#cIdentity-constraint_Definitions.
