= XML tags in geogebra.xml

Following document was generated by a modification of http://sourceforge.net/projects/xs3p/[xs3p] stylesheet. It
contains definitions of tags used in geogebra.xml, which is the most important part of xref:File_Format.adoc[.ggb
files]. For a brief introduction see xref:XML.adoc[XML reference]. Explanation of XML-related terms can be found
in xref:XML_Glossary.adoc[XML Glossary].

:toc:

== [#Global_Declarations]#Global Declarations#

=== [#Element:_algebraView]#Element: algebraView#

XML Instance Representation

[[Element:_algebraView_xibox]]
<algebraView>

<auxiliary

show="xs:boolean [0..1]"

/> [0..1]

<collapsed> xref:Common_XML_tags_and_types.adoc[stringVal] </collapsed> [0..1]

<mode

val="xref:Common_XML_tags_and_types.adoc[nonNegInt] [0..1]"

/> [0..1]

</algebraView>

=== [#Element:_axis]#Element: axis#

XML Instance Representation

[[Element:_axis_xibox]]
<axis

id="xref:Common_XML_tags_and_types.adoc[axisIds] [1]"

show="xs:boolean [0..1]"

label="xs:string [0..1]"

unitLabel="xs:string [0..1]"

tickStyle="xref:Common_XML_tags_and_types.adoc[tickStyles] [0..1]"

tickDistance="xs:double [0..1]"

axisCross="xs:double [0..1]"

positiveAxis="xs:boolean [0..1]"

showNumbers="xs:boolean [0..1]"

/>

=== [#Element:_euclidianView]#Element: euclidianView#

XML Instance Representation

[[Element:_euclidianView_xibox]]
<euclidianView>

<viewNumber

viewNo="xref:Common_XML_tags_and_types.adoc[positiveInt] [0..1]"

/> [0..1]

<xref:XML_tags_in_geogebra_xml.adoc[size]> ... </xref:XML_tags_in_geogebra_xml.adoc[size]> [0..1]

<coordSystem

xZero="xs:double [0..1]"

yZero="xs:double [0..1]"

scale="xs:double [0..1]"

xscale="xs:double [0..1]"

yscale="xs:double [0..1]"

/> [1]

<evSettings

axes="xs:boolean [0..1]"

grid="xs:boolean [0..1]"

gridIsBold="xs:boolean [0..1]"

pointCapturing="xref:Common_XML_tags_and_types.adoc[pointCapturings] [0..1]"

pointStyle="xref:Common_XML_tags_and_types.adoc[pointStyles] [0..1]"

rightAngleStyle="xref:Common_XML_tags_and_types.adoc[rightAngleStyles] [0..1]"

checkboxSize="xref:Common_XML_tags_and_types.adoc[nonNegInt] [0..1]"

gridType="xref:Common_XML_tags_and_types.adoc[gridTypes] [0..1]"

/> [1]

<bgColor> xref:Common_XML_tags_and_types.adoc[rgbColor] </bgColor> [1]

<axesColor> xref:Common_XML_tags_and_types.adoc[rgbColor] </axesColor> [1]

<gridColor> xref:Common_XML_tags_and_types.adoc[rgbColor] </gridColor> [1]

<lineStyle

axes="xref:Common_XML_tags_and_types.adoc[axisTypes] [0..1]"

grid="xref:Common_XML_tags_and_types.adoc[lineTypes] [0..1]"

/> [1]

<xref:XML_tags_in_geogebra_xml.adoc[axis]> ... </xref:XML_tags_in_geogebra_xml.adoc[axis]> [2..2]

<grid

distX="xs:double [0..1]"

distY="xs:double [0..1]"

distTheta="xs:double [0..1]"

/> [0..1]

</euclidianView>

=== [#Element:_euclidianView3D]#Element: euclidianView3D#

XML Instance Representation

[[Element:_euclidianView3D_xibox]]
<euclidianView3D>

<xref:XML_tags_in_geogebra_xml.adoc[size]> ... </xref:XML_tags_in_geogebra_xml.adoc[size]> [0..1]

<coordSystem

xZero="xs:double [0..1]"

yZero="xs:double [0..1]"

zZero="xs:double [0..1]"

scale="xs:double [0..1]"

xAngle="xs:double [0..1]"

zAngle="xs:double [0..1]"

/> [1]

<evSettings> ... </evSettings> [0..1]

<xref:XML_tags_in_geogebra_xml.adoc[axis]> ... </xref:XML_tags_in_geogebra_xml.adoc[axis]> [3..3]

<plate

show="xs:boolean [0..1]"

/> [1]

<bgColor> xref:Common_XML_tags_and_types.adoc[rgbColor] </bgColor> [1]

<grid

show="xs:boolean [0..1]"

/> [0..1]

<clipping

use="xs:boolean [0..1]"

show="xs:boolean [0..1]"

size="xref:Common_XML_tags_and_types.adoc[nonNegInt] [0..1]"

/> [1]

<projection

type="xref:Common_XML_tags_and_types.adoc[nonNegInt] [0..1]"

distance="xref:Common_XML_tags_and_types.adoc[nonNegInt] [0..1]"

separation="xref:Common_XML_tags_and_types.adoc[nonNegInt] [0..1]"

obliqueAngle="xs:double [0..1]"

obliqueFactor="xs:double [0..1]"

/> [1]

</euclidianView3D>

=== [#Element:_geogebra]#Element: geogebra#

XML Instance Representation

[[Element:_geogebra_xibox]]
<geogebra

format="xs:double [0..1]"

version="xs:string [0..1]"

id="xs:string [0..1]"

app="xs:string [0..1]"

platform="xs:string [0..1]"

>

<xref:XML_tags_in_geogebra_xml.adoc[gui]> ... </xref:XML_tags_in_geogebra_xml.adoc[gui]> [1]

<xref:XML_tags_in_geogebra_xml.adoc[euclidianView]> ... </xref:XML_tags_in_geogebra_xml.adoc[euclidianView]> [0..2]

<xref:XML_tags_in_geogebra_xml.adoc[euclidianView3D]> ... </xref:XML_tags_in_geogebra_xml.adoc[euclidianView3D]> [0..1]

<xref:XML_tags_in_geogebra_xml.adoc[spreadsheetView]> ... </xref:XML_tags_in_geogebra_xml.adoc[spreadsheetView]> [0..1]

<xref:XML_tags_in_geogebra_xml.adoc[algebraView]> ... </xref:XML_tags_in_geogebra_xml.adoc[algebraView]> [0..1]

<xref:XML_tags_in_geogebra_xml.adoc[keyboard]> ... </xref:XML_tags_in_geogebra_xml.adoc[keyboard]> [0..1]

<xref:XML_tags_in_geogebra_xml.adoc[kernel]> ... </xref:XML_tags_in_geogebra_xml.adoc[kernel]> [1]

<xref:XML_tags_in_geogebra_xml.adoc[scripting]> ... </xref:XML_tags_in_geogebra_xml.adoc[scripting]> [0..1]

<xref:XML_tags_in_geogebra_xml.adoc[euclidianView3D]> ... </xref:XML_tags_in_geogebra_xml.adoc[euclidianView3D]> [0..1]

<xref:Common_XML_tags_and_types.adoc[construction]> ... </xref:Common_XML_tags_and_types.adoc[construction]>
\[0..1]

</geogebra>

=== [#Element:_gui]#Element: gui#

XML Instance Representation

[[Element:_gui_xibox]]
<gui>

Start xref:XML_Glossary.adoc[Choice] [0..*]

<window

width="xref:Common_XML_tags_and_types.adoc[positiveInt] [1]"

height="xref:Common_XML_tags_and_types.adoc[positiveInt] [1]"

/> [0..1]

<perspectives> [0..1]

<xref:XML_tags_in_geogebra_xml.adoc[perspective]> ... </xref:XML_tags_in_geogebra_xml.adoc[perspective]> [1..*]

</perspectives>

<settings

ignoreDocument="xs:boolean [0..1]"

showTitleBar="xs:boolean [0..1]"

allowStyleBar="xs:boolean [0..1]"

/> [1]

<labelingStyle> xref:Common_XML_tags_and_types.adoc[intVal] </labelingStyle> [0..1]

<mouse

reverseWheel="xs:boolean [0..1]"

/> [1]

<consProtColumns

col0="xs:boolean [0..1]"

col1="xs:boolean [0..1]"

col2="xs:boolean [0..1]"

col3="xs:boolean [0..1]"

col4="xs:boolean [0..1]"

col5="xs:boolean [0..1]"

col6="xs:boolean [0..1]"

col7="xs:boolean [0..1]"

/> [0..1]

<consProtocol

useColors="xs:boolean [0..1]"

addIcons="xs:boolean [0..1]"

showOnlyBreakpoints="xs:boolean [0..1]"

/> [0..1]

<dataAnalysis

mode="xs:int [0..1]"

> [0..1]

<xref:XML_tags_in_geogebra_xml.adoc[variable]> ... </xref:XML_tags_in_geogebra_xml.adoc[variable]> [1]

</dataAnalysis>

<consProtNavigationBar

show="xs:boolean [0..1]"

playButton="xs:boolean [0..1]"

playDelay="xs:double [0..1]"

protButton="xs:boolean [0..1]"

consStep="xs:int [0..1]"

/> [0..1]

<show> ... </show> [0..1]

<xref:XML_tags_in_geogebra_xml.adoc[splitDivider]> ... </xref:XML_tags_in_geogebra_xml.adoc[splitDivider]> [0..1]

<xref:XML_tags_in_geogebra_xml.adoc[toolbar]> ... </xref:XML_tags_in_geogebra_xml.adoc[toolbar]> [0..1]

<font

size="xref:Common_XML_tags_and_types.adoc[positiveInt] [1]"

/> [0..1]

<menuFont

size="xs:int [1]"

/> [0..1]

<tooltipSettings

timeout="xs:int [0..1]"

language="xs:string [0..1]"

/> [0..1]

<graphicsSettings

javaLatexFonts="xs:boolean [0..1]"

/> [1]

End Choice

</gui>

=== [#Element:_kernel]#Element: kernel#

XML Instance Representation

[[Element:_kernel_xibox]]
<kernel>

Start xref:XML_Glossary.adoc[All] [0..1]

<uses3D> xref:Common_XML_tags_and_types.adoc[boolVal] </uses3D> [0..1]

<continuous> xref:Common_XML_tags_and_types.adoc[boolVal] </continuous> [0..1]

<usePathAndRegionParameters> xref:Common_XML_tags_and_types.adoc[stringVal] </usePathAndRegionParameters> [0..1]

<decimals> xref:Common_XML_tags_and_types.adoc[intVal] </decimals> [1]

<significantFigures> xref:Common_XML_tags_and_types.adoc[intVal] </significantFigures> [0..1]

<angleUnit

val="xref:Common_XML_tags_and_types.adoc[angleUnits] [1]"

/> [1]

<algebraStyle

val="xref:Common_XML_tags_and_types.adoc[algebraStyles] [1]"

spreadsheet="xref:Common_XML_tags_and_types.adoc[algebraStyles] [1]"

/> [0..1]

<coordStyle> xref:Common_XML_tags_and_types.adoc[intVal] </coordStyle> [1]

<startAnimation> xref:Common_XML_tags_and_types.adoc[boolVal] </startAnimation> [0..1]

<angleFromInvTrig> xref:Common_XML_tags_and_types.adoc[boolVal] </angleFromInvTrig> [0..1]

<localization

digits="xs:boolean [0..1]"

labels="xs:boolean [0..1]"

/> [0..1]

<casSettings

timeout="xs:double [0..1]"

expRoots="xs:boolean [0..1]"

/> [0..1]

End All

</kernel>

=== [#Element:_keyboard]#Element: keyboard#

XML Instance Representation

[[Element:_keyboard_xibox]]
<keyboard

language="xs:string [0..1]"

width="xref:Common_XML_tags_and_types.adoc[positiveInt] [0..1]"

height="xref:Common_XML_tags_and_types.adoc[positiveInt] [0..1]"

opacity="xs:double [0..1]"

show="xs:boolean [0..1]"

/>

=== [#Element:_pane]#Element: pane#

XML Instance Representation

[[Element:_pane_xibox]]
<pane

location="xs:string [1]"

divider="xref:Common_XML_tags_and_types.adoc[javaDouble] [0..1]"

orientation="xref:Common_XML_tags_and_types.adoc[nonNegInt] [0..1]"

/>

=== [#Element:_perspective]#Element: perspective#

XML Instance Representation

[[Element:_perspective_xibox]]
<perspective

id="xs:string [0..1]"

>

<panes> [1]

<xref:XML_tags_in_geogebra_xml.adoc[pane]> ... </xref:XML_tags_in_geogebra_xml.adoc[pane]> [1..*]

</panes>

<views> [1]

<xref:XML_tags_in_geogebra_xml.adoc[view]> ... </xref:XML_tags_in_geogebra_xml.adoc[view]> [1..*]

</views>

<toolbar> xref:XML_tags_in_geogebra_xml.adoc[toolbar] </toolbar> [1]

<show

axes="xs:boolean [0..1]"

grid="xs:boolean [0..1]"

/> [0..1]

<input

show="xs:boolean [0..1]"

cmd="xs:boolean [0..1]"

top="xref:XML_tags_in_geogebra_xml.adoc[algebraPosition] [0..1]"

/> [1]

<dockBar

show="xs:boolean [0..1]"

east="xs:boolean [0..1]"

/> [0..1]

</perspective>

=== [#Element:_scripting]#Element: scripting#

XML Instance Representation

[[Element:_scripting_xibox]]
<scripting

language="xs:string [0..1]"

disabled="xs:boolean [0..1]"

blocked="xs:boolean [0..1]"

/>

=== [#Element:_show]#Element: show#

Deprecated since 4.0, use perspectives insted.

XML Instance Representation

[[Element:_show_xibox]]
<show

algebraView="xs:boolean [0..1]"

spreadsheetView="xs:boolean [0..1]"

auxiliaryObjects="xs:boolean [0..1]"

algebraInput="xs:boolean [0..1]"

cmdList="xs:boolean [0..1]"

/>

=== [#Element:_size]#Element: size#

XML Instance Representation

[[Element:_size_xibox]]
<size

width="xref:Common_XML_tags_and_types.adoc[nonNegInt] [1]"

height="xref:Common_XML_tags_and_types.adoc[nonNegInt] [1]"

/>

=== [#Element:_splitDivider]#Element: splitDivider#

Deprecated since 4.0, use perspectives/perspective/panes insted.

XML Instance Representation

[[Element:_splitDivider_xibox]]
<splitDivider

loc="xref:Common_XML_tags_and_types.adoc[nonNegInt] [0..1]"

locVertical="xref:Common_XML_tags_and_types.adoc[nonNegInt] [0..1]"

loc2="xref:Common_XML_tags_and_types.adoc[positiveInt] [0..1]"

locVertical2="xref:Common_XML_tags_and_types.adoc[nonNegInt] [0..1]"

horizontal="xs:boolean [0..1]"

/>

=== [#Element:_spreadsheetView]#Element: spreadsheetView#

XML Instance Representation

[[Element:_spreadsheetView_xibox]]
<spreadsheetView>

<xref:XML_tags_in_geogebra_xml.adoc[size]> ... </xref:XML_tags_in_geogebra_xml.adoc[size]> [0..1]

<prefCellSize

width="xs:int [0..1]"

height="xs:int [0..1]"

/> [0..1]

<spreadsheetColumn

id="xref:Common_XML_tags_and_types.adoc[nonNegInt] [1]"

width="xref:Common_XML_tags_and_types.adoc[positiveInt] [1]"

/> [0..*]

<selection

hScroll="xs:integer [0..1]"

vScroll="xs:integer [0..1]"

column="xs:integer [0..1]"

row="xs:integer [0..1]"

/> [0..1]

<layout

showGrid="xs:boolean [0..1]"

showFormulaBar="xs:boolean [0..1]"

showHScrollBar="xs:boolean [0..1]"

showVScrollBar="xs:boolean [0..1]"

showBrowserPanel="xs:boolean [0..1]"

showColumnHeader="xs:boolean [0..1]"

showRowHeader="xs:boolean [0..1]"

allowSpecialEditor="xs:boolean [0..1]"

allowToolTips="xs:boolean [0..1]"

equalsRequired="xs:boolean [0..1]"

/> [0..1]

<spreadsheetCellFormat

formatMap="xs:string [0..1]"

/> [0..1]

</spreadsheetView>

=== [#Element:_toolbar]#Element: toolbar#

Deprecated since 4.0, use perspectives/perspective/toolbar insted.

XML Instance Representation

[[Element:_toolbar_xibox]]
<toolbar

str="xs:string [0..1]"

/>

=== [#Element:_variable]#Element: variable#

XML Instance Representation

[[Element:_variable_xibox]]
<variable>

<item

ranges="xs:string [0..1]"

/> [1..*]

</variable>

=== [#Element:_view]#Element: view#

XML Instance Representation

[[Element:_view_xibox]]
<view

id="xref:Common_XML_tags_and_types.adoc[positiveInt] [1]"

toolbar="xs:string [0..1]"

visible="xs:boolean [0..1]"

inframe="xs:boolean [0..1]"

stylebar="xs:boolean [0..1]"

location="xs:string [0..1]"

size="xref:Common_XML_tags_and_types.adoc[nonNegInt] [0..1]"

window="xs:string [0..1]"

/>

....
                    ==Global Definitions==
                    
....

=== [#Type:_toolbar]#Type: toolbar#

[cols=",",]
|===
|Super-types: |None
|Sub-types: |None
|===

XML Instance Representation

[[Type:_toolbar_xibox]]
<...

help="xs:boolean [0..1]"

show="xs:boolean [0..1]"

items="xs:string [0..1]"

position="xref:Common_XML_tags_and_types.adoc[nonNegInt] [0..1]"

/>

=== [#Type:_algebraPosition]#Type: algebraPosition#

[cols=",",]
|===
|Super-types: |xs:string < *algebraPosition* (by restriction)
|Sub-types: |None
|===

* Base XSD Type: string

* _pattern_ = true|false|algebra
